config/routes.rb
Rails.application.routes.draw do
  resources :permisos
  resources :rols
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permiso.rb
class Permiso < ApplicationRecord
    belongs_to :rol, optional: true
end

app/models/rol.rb
class Rol < ApplicationRecord
     has_many :permisos, :dependent => :destroy
   accepts_nested_attributes_for :permisos, allow_destroy: true

   def permisos_for_form
         collection = permisos.where(rol_id: id)
         collection.any? ? collection : permisos.build
   end

    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/permisos_controller.rb
class PermisosController < ApplicationController
  before_action :set_permiso, only: [:show, :edit, :update, :destroy]

  # GET /permisos
  # GET /permisos.json
  def index
    @permisos = Permiso.all
  end

  # GET /permisos/1
  # GET /permisos/1.json
  def show
  end

  # GET /permisos/new
  def new
    @permiso = Permiso.new
  end

  # GET /permisos/1/edit
  def edit
  end

  # POST /permisos
  # POST /permisos.json
  def create
    @permiso = Permiso.new(permiso_params)

    respond_to do |format|
      if @permiso.save
        format.html { redirect_to @permiso, notice: 'Permiso was successfully created.' }
        format.json { render :show, status: :created, location: @permiso }
      else
        format.html { render :new }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisos/1
  # PATCH/PUT /permisos/1.json
  def update
    respond_to do |format|
      if @permiso.update(permiso_params)
        format.html { redirect_to @permiso, notice: 'Permiso was successfully updated.' }
        format.json { render :show, status: :ok, location: @permiso }
      else
        format.html { render :edit }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisos/1
  # DELETE /permisos/1.json
  def destroy
    @permiso.destroy
    respond_to do |format|
      format.html { redirect_to permisos_url, notice: 'Permiso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso
      @permiso = Permiso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_params
      params.require(:permiso).permit(:crear, :actualizar, :eliminar, :consultar, :rol_id)
    end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
   @rol.permisos.build
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'Rol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
       params.require(:rol).permit(:nombre,
                	permisos_attributes: [:crear, :actualizar, :eliminar, :consultar, :rol_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SOFED</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/permisos/_form.html.erb
<%= form_with(model: permiso, local: true) do |form| %>
  <% if permiso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permiso.errors.count, "error") %> prohibited this permiso from being saved:</h2>

      <ul>
      <% permiso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :crear %>
    <%= form.check_box :crear, id: :permiso_crear %>
  </div>

  <div class="field">
    <%= form.label :actualizar %>
    <%= form.check_box :actualizar, id: :permiso_actualizar %>
  </div>

  <div class="field">
    <%= form.label :eliminar %>
    <%= form.check_box :eliminar, id: :permiso_eliminar %>
  </div>

  <div class="field">
    <%= form.label :consultar %>
    <%= form.check_box :consultar, id: :permiso_consultar %>
  </div>

  <div class="field">
    <%= form.label :rol_id %>
    <%= form.text_field :rol_id, id: :permiso_rol_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permisos/edit.html.erb
<h1>Editing Permiso</h1>

<%= render 'form', permiso: @permiso %>

<%= link_to 'Show', @permiso %> |
<%= link_to 'Back', permisos_path %>

app/views/permisos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permisos</h1>

<table>
  <thead>
    <tr>
      <th>Crear</th>
      <th>Actualizar</th>
      <th>Eliminar</th>
      <th>Consultar</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permisos.each do |permiso| %>
      <tr>
        <td><%= permiso.crear %></td>
        <td><%= permiso.actualizar %></td>
        <td><%= permiso.eliminar %></td>
        <td><%= permiso.consultar %></td>
        <td><%= permiso.rol %></td>
        <td><%= link_to 'Show', permiso %></td>
        <td><%= link_to 'Edit', edit_permiso_path(permiso) %></td>
        <td><%= link_to 'Destroy', permiso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permiso', new_permiso_path %>

app/views/permisos/new.html.erb
<h1>New Permiso</h1>

<%= render 'form', permiso: @permiso %>

<%= link_to 'Back', permisos_path %>

app/views/permisos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Crear:</strong>
  <%= @permiso.crear %>
</p>

<p>
  <strong>Actualizar:</strong>
  <%= @permiso.actualizar %>
</p>

<p>
  <strong>Eliminar:</strong>
  <%= @permiso.eliminar %>
</p>

<p>
  <strong>Consultar:</strong>
  <%= @permiso.consultar %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @permiso.rol %>
</p>

<%= link_to 'Edit', edit_permiso_path(@permiso) %> |
<%= link_to 'Back', permisos_path %>

app/views/rols/_form.html.erb
<%= form_with(model: rol, local: true) do |form| %>
  <% if rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
      <% rol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :rol_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rols/edit.html.erb
<h1>Editing Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Show', @rol %> |
<%= link_to 'Back', rols_path %>

app/views/rols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rols</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rols.each do |rol| %>
      <tr>
        <td><%= rol.nombre %></td>
        <td><%= link_to 'Show', rol %></td>
        <td><%= link_to 'Edit', edit_rol_path(rol) %></td>
        <td><%= link_to 'Destroy', rol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rol', new_rol_path %>

app/views/rols/new.html.erb
<h1>New Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Back', rols_path %>

app/views/rols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @rol.nombre %>
</p>

<%= link_to 'Edit', edit_rol_path(@rol) %> |
<%= link_to 'Back', rols_path %>